CREATE TABLE
  public.archives (
    id bigint,
    exoyear integer,
    arrivaldate DATE,
    arrivalid CHARACTER varying (10),
    sendersce CHARACTER varying (255),
    descentdate DATE,
    reportid CHARACTER varying (10),
    summondate DATE,
    actiontaken CHARACTER varying (255),
    measures CHARACTER varying (255),
    findingof CHARACTER varying (255),
    applicantname CHARACTER varying (255),
    applicantaddress CHARACTER varying (255),
    applicantcontact CHARACTER varying (255),
    locality CHARACTER varying (255),
    municipality CHARACTER varying (255),
    property0wner CHARACTER varying (255),
    propertytitle CHARACTER varying (255),
    propertyname CHARACTER varying (255),
    urbanplanningregulations CHARACTER varying (255),
    upr CHARACTER varying (255),
    zoning CHARACTER varying (255),
    surfacearea float,
    backfilledarea float,
    xv float,
    yv float,
    minutesid CHARACTER varying (10),
    minutesdate DATE,
    partsupplied CHARACTER varying (255),
    submissiondate DATE,
    destination CHARACTER varying (5),
    svr_fine float,
    svr_roalty float,
    invoicingid CHARACTER varying (10),
    invoicingdate DATE,
    fineamount float,
    roaltyamount float,
    convention CHARACTER varying (255),
    payementmethod CHARACTER varying (255),
    daftransmissiondate DATE,
    ref_quitus CHARACTER varying (255),
    sit_r CHARACTER varying (255),
    sit_a CHARACTER varying (255),
    commissiondate DATE,
    commissionopinion CHARACTER varying (255),
    recommandationobs CHARACTER varying (255),
    opfinal CHARACTER varying (255),
    opiniondfdate DATE,
    category CHARACTER varying (255)
  );